### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_source')     at new _Rect (rect.js:52:27)

### ISSUE THREAD

**Issue by jechazelle** [ckeditor/vite-plugin-ckeditor5#16] opened 2023-08-13 13:26 UTC
Hi,

I have an error when I execute ckeditor with vite-plugin-ckeditor5 when I click in the textarea from ckeditor:

ckeditor.tsx:169 TypeError: Cannot read properties of undefined (reading '_source')
    at new _Rect (rect.js:52:27)
    at getelementsintersectionrect.js:21:32
    at Array.map (<anonymous>)
    at getElementsIntersectionRect (getelementsintersectionrect.js:18:35)
    at StickyPanelView.checkIfShouldBeSticky (stickypanelview.js:116:38)
    at StickyPanelView.<anonymous> (stickypanelview.js:97:18)
    at StickyPanelView.fire (emittermixin.js:146:47)
    at StickyPanelView.set [as isActive] (observablemixin.js:72:30)
    at updateBoundObservableProperty (observablemixin.js:548:32)
    at observablemixin.js:574:25 {phase: 'runtime', willEditorRestart: true}

Build/ckeditor/ckeditor.ts

    import { ClassicEditor as ClassicEditorBase } from '@ckeditor/ckeditor5-editor-classic';
    import { Bold } from '@ckeditor/ckeditor5-basic-styles';

    export default class ClassicEditor extends ClassicEditorBase { }

    ClassicEditor.builtinPlugins = [
        Bold,
    ];

    ClassicEditor.defaultConfig = {
        toolbar: {
            items: [
                'bold',
            ],
        },
        language: 'en'
    };

vite.config.ts

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import react from '@vitejs/plugin-react';
import { viteStaticCopy } from 'vite-plugin-static-copy';
import * as path from 'path';
import ckeditor5 from '@ckeditor/vite-plugin-ckeditor5';

import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);

export default defineConfig({
  plugins: [
    laravel({
      input: 'resources/js/app.tsx',
      refresh: true,
    }),
    react(),
    viteStaticCopy({
      targets: [
        {
          src: path.resolve(__dirname, './resources/images'),
          dest: '../',
        },
        {
          src: path.resolve(__dirname, './resources/fonts'),
          dest: '../',
        },
      ],
    }),
    ckeditor5({ theme: require.resolve('@ckeditor/ckeditor5-theme-lark') })
  ],
  resolve: {
    alias: {
      '@': '/resources/js',
    },
  },
  build: {
    chunkSizeWarningLimit: 1000
  },
  define: {
    // By default, Vite doesn't include shims for NodeJS/
    // necessary for segment analytics lib to work
    global: {},
  },
});

```

post.ts

```
import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@/Build/ckeditor/ckeditor';

<CKEditor
  id="post-content"
  editor={ClassicEditor}
  data={translation.content}
  /* onChange={(event, editor: any) => {
      updateWysiwyg('content', editor.getData(), indexTranslation);
  }} */
 />
```

I use:
- vite@4.4.9
- react@18.2.0
- @ckeditor/ckeditor5-editor-classic@39.0.1
- @ckeditor/ckeditor5-basic-styles@39.0.1
- @ckeditor/ckeditor5-theme-lark@39.0.1
- @ckeditor/vite-plugin-ckeditor5@0.1.3

- node v16.20.2
- npm 8.19.4

tsconfig.json
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "rootDir": "./resources/js",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "paths": {
      "@/*": ["./resources/js/*"]
    },
    "types": [
        "node",
        "vite/client",
    ]
  }
}
```

**Comment by LukaszGudel** [comment] 2023-08-16 11:17
Duplicate of https://github.com/ckeditor/vite-plugin-ckeditor5/issues/17.

**Closed by LukaszGudel** 2023-08-16 11:17 UTC
